---
- name: "1M event rules"
  hosts: all
  sources:
    - name: generic
      ansible.eda.generic:
        create_index: i
        #event_delay: .0000000000001
        loop_count: 200000
        loop_delay: .0000001
        payload:
          - name: fred
  rules:
    - name: r1
      condition: event.i is defined
      action:
        none:
