---
- name: "1M event rules"
  hosts: all
  sources:
    - name: generic
      ansible.eda.generic:
        create_index: i
        event_delay: .00015
        loop_count: 200000
        payload:
          - name: fred
  rules:
    - name: r1
      condition: event.i is defined
      action:
        none:
