---
- name: "1M event rules"
  hosts: all
  sources:
    - name: range
      ansible.eda.range:
        limit: 200000
  rules:
    - name: r1
      condition: event.i is defined
      action:
        none:
