---
- name: Hello Controller
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
  rules:
    - name: "Run job template"
      condition: event.i < 101
      action:
        run_job_template:
          name: Chatty3
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
  execution_strategy: "parallel"
...
